version: 2.1

jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: chmod 777 infrastructure.sh
      - run:
          name: Create Cloudformation Stack
          command: ./infrastructure.sh

workflows:
  myWorkflow:
    jobs:
      - myjob1
      - myjob2
